// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	Comid        string `json:"comid"`
	Companygroup string `json:"companygroup"`
	Companyname  string `json:"companyname"`
	Comcode      string `json:"comcode"`
}

type NewCompany struct {
	Comid        string `json:"comid"`
	Companygroup string `json:"companygroup"`
	Companyname  string `json:"companyname"`
	Comcode      string `json:"comcode"`
}
